# Generated by Django 2.1 on 2018-08-06 03:20

import common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('entry', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_dictionary_created_related', related_query_name='dictionary_dictionarys_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_dictionary_modified_related', related_query_name='dictionary_dictionarys_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_dictionary_owner_related', related_query_name='dictionary_dictionarys_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
    ]
