# Generated by Django 2.1 on 2018-08-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='entry',
            new_name='dict_entry',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='key',
            new_name='dict_key',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='value',
            new_name='dict_value',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='dict_remark',
            field=models.CharField(default='', max_length=500),
        ),
    ]
